### ISSUE TITLE
Kanalictl doesn't show correct version

### ISSUE THREAD

**Issue by frankgreco** [northwesternmutual/kanali#106]
```sh
$ ./kanalictl version
 ()
```

**Comment by hartalex** [comment]
## Steps to reproduce
#### Set the Version Number Environment Variable
- export RELEASE=123.456
#### Comment out S3 deploy commands
- edit hack/distro.sh script and comment out "aws s3" commands. lines 25, 38, 40
#### Build Kanali Binaries
- ./hack/distro.sh
#### Run one of the Kanali Binaries
- ./kanalictl_amd64 version 

**expected output:**  
   123.456 (c50e3ad)  # Note that the (c50e3ad) changes and should match the latest git commit

 **actual output:** 
 ()
