### ISSUE TITLE
Migrate to CustomResourceDefinitions (CRDs)

### ISSUE THREAD

**Issue by frankgreco** [northwesternmutual/kanali#3]
Starting in Kubernetes 1.7, [Custom Resource Definitions](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/) begin to replace [Third Party Resources](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/). This issue is to track to migration from TPRs to CRDs.

Kanali still needs to support TPRs for Kubernetes versions <= 1.7 and so Kanali should query the Kubernetes API server for its version and create either a TPR or CRD based on the result.

**Comment by frankgreco** [comment]
#46 may need to be completed prior to to this migration.

**Comment by roffe** [comment]
Is there any progress on #46 & this?

**Comment by frankgreco** [comment]
@roffe 

Development on this issue has just began (you'll see linked commits shortly). Kubernetes v1.8 is creeping up and so a priority label has been added to this issue and will be done shortly. I'll need to give people enough time to upgrade to the latest version of Kanali (that includes this change) before v1.8 officially comes out.

Concerning #46, I am waiting for [this issue](https://github.com/kubernetes/client-go/issues/276) to be commented on or resolved as I would like to use the *client-go* libraries in the client upgrade. However, as the Kubernetes v1.8 release approaches, I'll need to find a workaround very shortly if that issue is not resolved.

**Comment by roffe** [comment]
Thank you for the quick reply @frankgreco!

Looking forward to the updates & have began testing Kanali with TPR.
The CRD part is a little blocker but seeing the issue is alive and prioritised enables me to keep testing with a good feeling in my stomach.

Keep up the good work!

**Comment by frankgreco** [comment]
@roffe there is a branch that exists, [client-go4](https://git.nmlv.nml.com/infrastructure/ansible-kubernetes-config/merge_requests/330), that has a majority of the work for this done already.

**Comment by frankgreco** [comment]
Update:

This change is mostly done and currently sits in the `go-client4` branch. Just waiting for the steps highlighted in [kubernetes/apiextensions-server#12](https://github.com/kubernetes/apiextensions-apiserver/issues/12#issuecomment-334206978) to be completed before
