### ISSUE TITLE
Helm template uses wrong ClusterRole name in ClusterRoleBinding

### ISSUE THREAD

**Issue by brtnshrdr** [northwesternmutual/kanali#75]
I could be wrong here, but after having troubles trying to use Helm to deploy this, it seems that the Kanali `ClusterRoleBinding` is using the wrong `name` for the `roleRef` here:
https://github.com/northwesternmutual/kanali/blob/master/helm/templates/clusterRoleBinding.yaml#L12
(Pointing to what I assume should be the name of the `ClusterRole` here:
https://github.com/northwesternmutual/kanali/blob/master/helm/templates/clusterRole.yaml#L6

I switched the `name` field locally to just be `kanali` and it no longer gives me the following error
`Fail to create TPR: the server does not allow access to the requested resource (post thirdpartyresources.extensions) google`

This is in Google Clouds Container Engine (I received the same error in Kubernetes versions 1.6.11, 1.7.6, 1.7.8 when RBAC is turned on)

**Comment by frankgreco** [comment]
@brtnshrdr #76 should fix this

**Comment by brtnshrdr** [comment]
Thanks!
